# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         AxKit2
version:      1.0
version_from: lib/AxKit2.pm
installdirs:  site
requires:
    Danga::Socket:                 1.52
    XML::LibXML:                   1.59
    XML::LibXML::XPathContext:     0.07
    XML::LibXSLT:                  1.59

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
